* IS GROWTH "BALANCED"?
	* CURRENT ACCOUNT
	* GOODS AND SERVICES BALANCE
	* EXTERNAL DEBT (@ WORLD DEBT TABLES)
	* TERMS OF TRADE

* WHAT HAPPENNED DURING THE BREAKS?
	* EXCHANGE RATE
	* TERMS OF TRADE
	* EXPORTS/IMPORTS
	* FDI
	* INFLATION
	* AID
	* RESERVES
	* INTEREST RATES

* CHARACTERIZATION OF EXPORT STRUCTURE
	* CORRELATION BETWEEN GDP GROWTH AND EXPORTS GROWTH

* GOOD LUCK OF GOOD POLICIES?
	* 
